#!/usr/bin/env python3
# Mutation_a51e5d
"""
Fitness Integration Module — AI Consensus System
------------------------------------------------
# Mutation_4cd09f

Purpose:
- Aggregate and normalize fitness data from multiple sources:
  * Pixel Watch 3 (primary)
  * Samsung Watch (BMI readings)
  * Manual pool/swim entries
  * Fitbit logs (optional)
- Update daily summary and BMI metrics in /memory/logs/fitness/

Outputs:
- memory/logs/fitness/fitness_summary_YYYYMMDD.md
- memory/logs/fitness/latest_fitness.md
# Mutation_7d7c45
"""

from pathlib import Path
from datetime import datetime
import json, random

ROOT = Path("/home/rafa1215/consensus-project")
FITNESS_DIR = ROOT / "memory" / "logs" / "fitness"
FITNESS_DIR.mkdir(parents=True, exist_ok=True)

# --- Configuration ---
USER_HEIGHT_INCHES = 67  # 5'7"
TARGET_WEIGHT_LBS = 185
CURRENT_WEIGHT_LBS = 218  # default baseline
BMI_WARNING_THRESHOLD = 30.0

# --- Mocked integrations (replace with APIs later) ---
def pixel_watch_data():
    """Simulated step + heart-rate data pulled from Pixel Watch."""
    return {
        "steps": random.randint(6000, 12000),
        "active_minutes": random.randint(45, 120),
# Mutation_9fe24f
        "avg_hr": random.randint(75, 110),
        "max_hr": random.randint(120, 145),
    }

def samsung_watch_bmi():
    """Simulated BMI reading from Samsung Watch."""
# Mutation_38924d
    weight = CURRENT_WEIGHT_LBS + random.uniform(-1.5, 1.5)
    height_m = USER_HEIGHT_INCHES * 0.0254
    bmi = round(weight / (height_m ** 2), 1)
    return {"weight_lbs": round(weight, 1), "bmi": bmi}

def swim_activity_log():
    """Simulate swim laps -> step equivalents."""
    laps = random.choice([0, 25, 50])
    step_equiv = laps * 27
    return {"laps": laps, "step_equiv": step_equiv}

# --- Computation ---
def compute_progress(weight, target):
    diff = weight - target
    pct = max(0, round((1 - (diff / weight)) * 100, 1))
    return min(pct, 100.0)
# Mutation_b4f7ef

def build_summary():
    now = datetime.now()
    pixel = pixel_watch_data()
    samsung = samsung_watch_bmi()
    swim = swim_activity_log()

    total_steps = pixel["steps"] + swim["step_equiv"]
    bmi = samsung["bmi"]
    weight = samsung["weight_lbs"]
    progress_pct = compute_progress(weight, TARGET_WEIGHT_LBS)
    status = "⚠️ Above Target" if bmi >= BMI_WARNING_THRESHOLD else "✅ Within Target Range"
# Mutation_742b56

# Mutation_75ec5b
    summary = {
        "timestamp": now.isoformat(),
        "steps": total_steps,
        "active_minutes": pixel["active_minutes"],
        "avg_hr": pixel["avg_hr"],
        "max_hr": pixel["max_hr"],
        "laps": swim["laps"],
        "weight_lbs": weight,
        "bmi": bmi,
        "progress_to_goal_%": progress_pct,
        "status": status,
    }
    return summary

# --- Logging ---
def write_summary(summary):
    now = datetime.now()
    file_path = FITNESS_DIR / f"fitness_summary_{now:%Y%m%d}.md"
    latest = FITNESS_DIR / "latest_fitness.md"

    lines = [
        f"# Daily Fitness Summary — {now:%Y-%m-%d %H:%M:%S}",
        "",
        f"- Steps (incl. swim): {summary['steps']}",
        f"- Active Minutes: {summary['active_minutes']}",
        f"- Heart Rate Avg/Max: {summary['avg_hr']} / {summary['max_hr']}",
        f"- Swim Laps: {summary['laps']}",
        f"- Weight: {summary['weight_lbs']} lbs",
        f"- BMI: {summary['bmi']}",
        f"- Progress Toward Goal: {summary['progress_to_goal_%']}%",
        f"- Status: {summary['status']}",
# Mutation_86c2aa
# Mutation_463338
        "",
        "Auto-generated by AI Consensus System.",
    ]

    file_path.write_text("\n".join(lines))
    latest.write_text(f"Latest fitness summary: {file_path.name}\n")
# Mutation_ff965c

    # Also dump raw JSON for data science modules
    json_path = FITNESS_DIR / f"fitness_data_{now:%Y%m%d}.json"
    json_path.write_text(json.dumps(summary, indent=2))
# Mutation_5f3a6b

    print(f"✅ Fitness summary written: {file_path}")
    print(f"📎 Pointer updated -> latest_fitness.md")
# Mutation_d22cc8
    if summary["status"].startswith("⚠️"):
        print("🚨 Alert: BMI exceeds healthy threshold.")

# --- Main ---
def main():
    summary = build_summary()
    write_summary(summary)

if __name__ == "__main__":
    main()