#!/usr/bin/env python3
"""
Fitness Integration Module — AI Consensus System

Production-safe fitness aggregation.

Rules:
- Never fabricate Pixel Watch, Samsung Watch, swim, weight, BMI, or step data.
- Read only genuine records already written to memory/logs/fitness/daily_metrics.jsonl.
- If no current-day source records exist, do not overwrite an existing summary.
- Preserve the established output paths used by downstream agents.
"""

from __future__ import annotations

from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any

ROOT = Path("/home/rafa1215/consensus-project")
FITNESS_DIR = ROOT / "memory" / "logs" / "fitness"
FITNESS_DIR.mkdir(parents=True, exist_ok=True)

DAILY_METRICS = FITNESS_DIR / "daily_metrics.jsonl"


def quarantine_legacy_simulated_outputs(now: datetime) -> list[Path]:
    """Move known prototype-generated fitness outputs out of the live evidence path."""
    quarantine_dir = FITNESS_DIR / "archive" / "simulated"
    moved: list[Path] = []

    summary = FITNESS_DIR / f"fitness_summary_{now:%Y%m%d}.md"
    raw_json = FITNESS_DIR / f"fitness_data_{now:%Y%m%d}.json"

    if summary.is_file():
        text = summary.read_text(encoding="utf-8", errors="replace")
        legacy_signature = (
            "Steps (incl. swim):" in text
            and "Progress Toward Goal:" in text
            and "Auto-generated by AI Consensus System." in text
        )
        if legacy_signature:
            quarantine_dir.mkdir(parents=True, exist_ok=True)
            target = quarantine_dir / summary.name
            summary.replace(target)
            moved.append(target)

            if raw_json.is_file():
                json_target = quarantine_dir / raw_json.name
                raw_json.replace(json_target)
                moved.append(json_target)

            latest = FITNESS_DIR / "latest_fitness.md"
            if latest.is_file() and summary.name in latest.read_text(encoding="utf-8", errors="replace"):
                latest.unlink()

    return moved


def parse_timestamp(value: Any) -> datetime | None:
    if not isinstance(value, str) or not value.strip():
        return None
    raw = value.strip().replace("Z", "+00:00")
    try:
        dt = datetime.fromisoformat(raw)
    except ValueError:
        return None
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(timezone.utc)


def current_day_records(now: datetime) -> list[dict[str, Any]]:
    if not DAILY_METRICS.is_file():
        return []

    today = now.astimezone(timezone.utc).date()
    records: list[dict[str, Any]] = []

    for raw_line in DAILY_METRICS.read_text(encoding="utf-8", errors="replace").splitlines():
        if not raw_line.strip():
            continue
        try:
            obj = json.loads(raw_line)
        except json.JSONDecodeError:
            continue
        if not isinstance(obj, dict):
            continue

        ts = parse_timestamp(obj.get("timestamp") or obj.get("time") or obj.get("ts"))
        if ts is None or ts.date() != today:
            continue
        records.append(obj)

    return records


def numeric(record: dict[str, Any], *keys: str) -> float | None:
    for key in keys:
        value = record.get(key)
        if isinstance(value, (int, float)) and not isinstance(value, bool):
            return float(value)
    return None


def build_summary(records: list[dict[str, Any]], now: datetime) -> dict[str, Any] | None:
    if not records:
        return None

    steps = 0
    active_minutes = 0.0
    swim_laps = 0
    avg_hr_values: list[float] = []
    max_hr_values: list[float] = []
    weight_lbs: float | None = None
    bmi: float | None = None
    genuine_fields = 0

    for record in records:
        value = numeric(record, "steps", "step_count")
        if value is not None:
            steps += int(value)
            genuine_fields += 1

        value = numeric(record, "active_minutes", "mvpa_minutes", "zone_minutes")
        if value is not None:
            active_minutes += value
            genuine_fields += 1

        value = numeric(record, "swim_laps", "laps", "pool_laps")
        if value is not None:
            swim_laps += int(value)
            genuine_fields += 1

        value = numeric(record, "avg_hr", "average_hr", "heart_rate_avg")
        if value is not None:
            avg_hr_values.append(value)
            genuine_fields += 1

        value = numeric(record, "max_hr", "heart_rate_max")
        if value is not None:
            max_hr_values.append(value)
            genuine_fields += 1

        value = numeric(record, "weight_lbs")
        if value is not None:
            weight_lbs = value
            genuine_fields += 1

        value = numeric(record, "bmi")
        if value is not None:
            bmi = value
            genuine_fields += 1

    if genuine_fields == 0:
        return None

    return {
        "timestamp": now.isoformat(),
        "source": str(DAILY_METRICS),
        "records": len(records),
        "steps": steps,
        "active_minutes": round(active_minutes, 1),
        "avg_hr": round(sum(avg_hr_values) / len(avg_hr_values), 1) if avg_hr_values else None,
        "max_hr": max(max_hr_values) if max_hr_values else None,
        "laps": swim_laps,
        "weight_lbs": weight_lbs,
        "bmi": bmi,
    }


def write_summary(summary: dict[str, Any], now: datetime) -> None:
    file_path = FITNESS_DIR / f"fitness_summary_{now:%Y%m%d}.md"
    latest = FITNESS_DIR / "latest_fitness.md"

    lines = [
        f"# Daily Fitness Summary — {now:%Y-%m-%d %H:%M:%S} UTC",
        "",
        f"- Source: {summary['source']}",
        f"- Source records: {summary['records']}",
    ]

    if summary["steps"] > 0:
        lines.append(f"- Steps: {summary['steps']}")
    if summary["active_minutes"] > 0:
        lines.append(f"- Active Minutes: {summary['active_minutes']:.0f}")
    if summary["avg_hr"] is not None or summary["max_hr"] is not None:
        lines.append(
            f"- Heart Rate Avg/Max: "
            f"{summary['avg_hr'] if summary['avg_hr'] is not None else 'n/a'} / "
            f"{summary['max_hr'] if summary['max_hr'] is not None else 'n/a'}"
        )
    if summary["laps"] > 0:
        lines.append(f"- Swim Laps: {summary['laps']}")
    if summary["weight_lbs"] is not None:
        lines.append(f"- Weight: {summary['weight_lbs']:.1f} lbs")
    if summary["bmi"] is not None:
        lines.append(f"- BMI: {summary['bmi']:.1f}")

    lines.extend([
        "",
        "Auto-generated from genuine source records by AI Consensus System.",
    ])

    file_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    latest.write_text(f"Latest fitness summary: {file_path.name}\n", encoding="utf-8")

    json_path = FITNESS_DIR / f"fitness_data_{now:%Y%m%d}.json"
    json_path.write_text(json.dumps(summary, indent=2) + "\n", encoding="utf-8")

    print(f"Fitness summary written: {file_path}")
    print(f"Source: {DAILY_METRICS} ({summary['records']} current-day record(s))")


def main() -> int:
    now = datetime.now(timezone.utc)
    quarantined = quarantine_legacy_simulated_outputs(now)
    for path in quarantined:
        print(f"QUARANTINED legacy simulated fitness output: {path}")

    records = current_day_records(now)
    summary = build_summary(records, now)

    if summary is None:
        print(
            "SKIP: no genuine current-day fitness source data found; "
            "no production fitness summary was written."
        )
        return 0

    write_summary(summary, now)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
