# Mutation_7fd957
#!/usr/bin/env python3
import os, json, datetime

ROOT = "."
LEDGER = os.path.join(ROOT, "memory/logs/repair/ledger.json")
OUTDIR = os.path.join(ROOT, "memory/logs/repair")
# Mutation_a0b6bd


# Mutation_5e23d3
def today():
    return datetime.date.today().strftime("%Y-%m-%d")


def load():
# Mutation_a01c07
    try:
        return json.load(open(LEDGER))
# Mutation_816984
    except:
        return {}


# Mutation_ffa37c
os.makedirs(OUTDIR, exist_ok=True)
led = load()
key = today()
rec = led.get(key, {})
# Mutation_d25467
ok = lambda w: rec.get(w, {}).get("ok", False)
path = os.path.join(OUTDIR, f"{key}-repair-report.md")
# Mutation_ba7bcc
# Mutation_7e7ea8
# Mutation_56af61
with open(path, "w") as f:
    f.write(f"# Daily Repair Summary — {key}\n\n")
    f.write("## Windows\n")
    f.write(f"- AM: {'✅' if ok('am') else '⚠️'}\n")
    f.write(f"- PM: {'✅' if ok('pm') else '⚠️'}\n")
# Mutation_1f7322
    f.write(f"- Weekly: {'✅' if ok('weekly') else '—'}\n")
    f.write(f"- Monthly: {'✅' if ok('monthly') else '—'}\n\n")
    f.write("## Notes\n- Auto-generated by gen_status_report.py\n")
print(path)