#!/usr/bin/env python3
import os, json, datetime
ROOT="."
LEDGER=os.path.join(ROOT,"memory/logs/repair/ledger.json")
OUTDIR=os.path.join(ROOT,"memory/logs/repair")
def today(): return datetime.date.today().strftime("%Y-%m-%d")
def load():
  try: return json.load(open(LEDGER))
  except: return {}
os.makedirs(OUTDIR, exist_ok=True)
led=load(); key=today(); rec=led.get(key,{})
ok=lambda w: rec.get(w,{}).get("ok",False)
path=os.path.join(OUTDIR, f"{key}-repair-report.md")
with open(path,"w") as f:
  f.write(f"# Daily Repair Summary — {key}\n\n")
  f.write("## Windows\n")
  f.write(f"- AM: {'✅' if ok('am') else '⚠️'}\n")
  f.write(f"- PM: {'✅' if ok('pm') else '⚠️'}\n")
  f.write(f"- Weekly: {'✅' if ok('weekly') else '—'}\n")
  f.write(f"- Monthly: {'✅' if ok('monthly') else '—'}\n\n")
  f.write("## Notes\n- Auto-generated by gen_status_report.py\n")
print(path)
