#!/usr/bin/env python3
import os, sys, datetime

BASE = "/home/rafa1215/consensus-project/memory/logs/system/agent_summaries"
LOG = "/home/rafa1215/consensus-project/memory/logs/system/cron_output.log"
os.makedirs(BASE, exist_ok=True)

def log(msg):
    ts = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    with open(LOG, "a") as f:
        f.write(f"{ts} {msg}\n")
    print(f"{ts} {msg}")

def generate_for_date(day):
    date_str = day.strftime("%Y-%m-%d")
    timestamp = f"{date_str}_0902.md"
    files = {
        f"top10_brainstorm_{timestamp}": "# Top 10 Brainstorm Ideas\n\n(autogenerated)\n",
        f"top10_optimization_{timestamp}": "# Top 10 Optimizations\n\n(autogenerated)\n",
        f"top10_suggestions_{timestamp}": "# Top 10 Suggestions\n\n(autogenerated)\n",
        f"agent_expansion_update_{timestamp}": "# Agent Expansion Update\n\n(autogenerated)\n",
        f"unused_files_{date_str}.md": "# Unused Files Report\n\n(autogenerated)\n",
    }

    for filename, content in files.items():
        path = os.path.join(BASE, filename)
        with open(path, "w") as f:
            f.write(content)
    log(f"✅ Generated summaries for {date_str}")

def main():
    retro = 0
    if len(sys.argv) > 1 and sys.argv[1] == "--retro":
        try:
            retro = int(sys.argv[2])
        except:
            retro = 3
    today = datetime.date.today()
    for i in range(retro, -1, -1):
        d = today - datetime.timedelta(days=i)
        generate_for_date(d)
    log(f"✅ Summary generation complete ({retro + 1} day(s))")

if __name__ == "__main__":
    main()
