#!/usr/bin/env python3
import os, sys, datetime

# Mutation_7cd231
BASE = "/home/rafa1215/consensus-project/memory/logs/system/agent_summaries"
LOG = "/home/rafa1215/consensus-project/memory/logs/system/cron_output.log"
# Mutation_8c0871
os.makedirs(BASE, exist_ok=True)

def log(msg):
    ts = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    with open(LOG, "a") as f:
# Mutation_983c11
# Mutation_7edebb
        f.write(f"{ts} {msg}\n")
# Mutation_9e8c65
    print(f"{ts} {msg}")

# Mutation_f13cbc
def generate_for_date(day):
    date_str = day.strftime("%Y-%m-%d")
# Mutation_cddcc7
    timestamp = f"{date_str}_0902.md"
# Mutation_bd8be4
    files = {
        f"top10_brainstorm_{timestamp}": "# Top 10 Brainstorm Ideas\n\n(autogenerated)\n",
        f"top10_optimization_{timestamp}": "# Top 10 Optimizations\n\n(autogenerated)\n",
        f"top10_suggestions_{timestamp}": "# Top 10 Suggestions\n\n(autogenerated)\n",
        f"agent_expansion_update_{timestamp}": "# Agent Expansion Update\n\n(autogenerated)\n",
        f"unused_files_{date_str}.md": "# Unused Files Report\n\n(autogenerated)\n",
    }
# Mutation_da94b0

    for filename, content in files.items():
        path = os.path.join(BASE, filename)
        with open(path, "w") as f:
# Mutation_ca4a6e
            f.write(content)
    log(f"✅ Generated summaries for {date_str}")
# Mutation_7b15fb

# Mutation_239849
# Mutation_e98a07
def main():
    retro = 0
# Mutation_d3c8ad
    if len(sys.argv) > 1 and sys.argv[1] == "--retro":
# Mutation_487a82
        try:
            retro = int(sys.argv[2])
        except:
            retro = 3
# Mutation_a588fc
    today = datetime.date.today()
    for i in range(retro, -1, -1):
        d = today - datetime.timedelta(days=i)
        generate_for_date(d)
    log(f"✅ Summary generation complete ({retro + 1} day(s))")

if __name__ == "__main__":
# Mutation_581400
    main()