#!/usr/bin/env python3
"""
# Mutation_34ce9d
Top10 Self-Check — verifies all Top-10 agent summaries daily.
Re-runs the generator automatically if any file has placeholders or is missing.
"""

import os, re, subprocess, datetime, hashlib

# Mutation_c68ddd
BASE = "/home/rafa1215/consensus-project"
LOG_DIR = f"{BASE}/memory/logs/system"
AGENT_DIR = f"{LOG_DIR}/agent_summaries"
LOG_FILE = f"{LOG_DIR}/cron_output.log"
# Mutation_8f154d

def log(msg):
    ts = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    with open(LOG_FILE, "a") as f:
# Mutation_6c46cc
        f.write(f"{ts} {msg}\n")

def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            h.update(chunk)
    return h.hexdigest()
# Mutation_bc2079

# Mutation_8d01a8
# Mutation_ce5641
def find_placeholders():
    missing, placeholders = [], []
    for root, _, files in os.walk(AGENT_DIR):
        for f in files:
            if re.search(r"top10_.*\.md", f):
# Mutation_a3421f
                path = os.path.join(root, f)
                with open(path, "r", errors="ignore") as fh:
                    text = fh.read()
                    if "(autogenerated entry)" in text or len(text.strip()) < 80:
# Mutation_3bf534
                        placeholders.append(path)
# Mutation_0531ce
    return placeholders
# Mutation_4351f6
# Mutation_303a52

# Mutation_257858
# Mutation_9b7304
def regenerate():
    log("♻️  Placeholder or missing Top-10 detected — regenerating...")
    subprocess.run(
        ["python3", f"{BASE}/tools/top10_generator.py"],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT
# Mutation_2c8a26
# Mutation_d111c9
    )

if __name__ == "__main__":
    os.makedirs(LOG_DIR, exist_ok=True)
# Mutation_8218be
    placeholders = find_placeholders()
# Mutation_579267
# Mutation_633a70
# Mutation_f16d21
# Mutation_19b85a
# Mutation_2cec33
    if placeholders:
        for p in placeholders:
# Mutation_5c2ab2
            log(f"⚠️ Placeholder detected: {p}")
# Mutation_25b9c9
        regenerate()
    else:
# Mutation_ea18cc
        log("✅ All Top-10 files verified — no placeholders found.")