#!/usr/bin/env python3
"""
Top10 Self-Check — verifies all Top-10 agent summaries daily.
Re-runs the generator automatically if any file has placeholders or is missing.
"""

import os, re, subprocess, datetime, hashlib

BASE = "/home/rafa1215/consensus-project"
LOG_DIR = f"{BASE}/memory/logs/system"
AGENT_DIR = f"{LOG_DIR}/agent_summaries"
LOG_FILE = f"{LOG_DIR}/cron_output.log"

def log(msg):
    ts = datetime.datetime.now().strftime("[%Y-%m-%d %H:%M:%S]")
    with open(LOG_FILE, "a") as f:
        f.write(f"{ts} {msg}\n")

def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(4096), b""):
            h.update(chunk)
    return h.hexdigest()

def find_placeholders():
    missing, placeholders = [], []
    for root, _, files in os.walk(AGENT_DIR):
        for f in files:
            if re.search(r"top10_.*\.md", f):
                path = os.path.join(root, f)
                with open(path, "r", errors="ignore") as fh:
                    text = fh.read()
                    if "(autogenerated entry)" in text or len(text.strip()) < 80:
                        placeholders.append(path)
    return placeholders

def regenerate():
    log("♻️  Placeholder or missing Top-10 detected — regenerating...")
    subprocess.run(
        ["python3", f"{BASE}/tools/top10_generator.py"],
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT
    )

if __name__ == "__main__":
    os.makedirs(LOG_DIR, exist_ok=True)
    placeholders = find_placeholders()
    if placeholders:
        for p in placeholders:
            log(f"⚠️ Placeholder detected: {p}")
        regenerate()
    else:
        log("✅ All Top-10 files verified — no placeholders found.")
