#!/usr/bin/env python3
"""
vpn_status_reporter.py

Generates a high-level project status report for the AutoConnectVPN feature.

It summarizes:
- Latest VPN functional test report (vpn_test_report*.md)
- Latest VPN load/stress test report (vpn_load_stress_report*.md)
- Presence and freshness of security_audit.log generated by security_audit_runner.py

Output:
- /home/rafa1215/consensus-project/memory/logs/status/vpn_status_report.md
"""

import datetime
from datetime import timezone
from pathlib import Path
from typing import Optional, Tuple, List

# Hardcode the known-good base path for this project
PROJECT_ROOT = Path("/home/rafa1215/consensus-project").resolve()
SYSTEM_LOG_DIR = PROJECT_ROOT / "memory" / "logs" / "system"
STATUS_DIR = PROJECT_ROOT / "memory" / "logs" / "status"
STATUS_DIR.mkdir(parents=True, exist_ok=True)

SECURITY_AUDIT_LOG = SYSTEM_LOG_DIR / "security_audit.log"

DEBUG = True  # prints what files it sees for easier troubleshooting


def utc_now() -> datetime.datetime:
    return datetime.datetime.now(timezone.utc)


def list_all_files() -> List[Path]:
    """Return all files in SYSTEM_LOG_DIR."""
    files = sorted(p for p in SYSTEM_LOG_DIR.iterdir() if p.is_file())
    if DEBUG:
        print(f"[DEBUG] SYSTEM_LOG_DIR = {SYSTEM_LOG_DIR}")
        print("[DEBUG] All files in SYSTEM_LOG_DIR:")
        for f in files:
            print(f"  - {f.name}")
    return files


def find_latest_with_prefix(prefix: str) -> Optional[Path]:
    """
    Scan SYSTEM_LOG_DIR and return the latest file whose name starts with prefix
    and ends with .md.
    """
    files = list_all_files()
    candidates = [f for f in files if f.name.startswith(prefix) and f.suffix == ".md"]
    if DEBUG:
        print(f"[DEBUG] Prefix '{prefix}' candidates:")
        for c in candidates:
            print(f"  - {c.name}")
    return candidates[-1] if candidates else None


def audit_log_freshness(hours_threshold: float = 31 * 24) -> Tuple[bool, Optional[float]]:
    """
    Check if security_audit.log exists and is fresh within hours_threshold.
    Returns (exists_and_fresh, age_hours or None).
    """
    if not SECURITY_AUDIT_LOG.exists():
        return False, None

    now_ts = utc_now().timestamp()
    mtime = SECURITY_AUDIT_LOG.stat().st_mtime
    age_hours = (now_ts - mtime) / 3600.0
    is_fresh = age_hours <= hours_threshold
    return is_fresh, age_hours


def main() -> None:
    now = utc_now()
    date_str = now.date().isoformat()

    # Look for both timestamp and *_latest files by using base prefixes
    latest_func = find_latest_with_prefix("vpn_test_report")
    latest_load = find_latest_with_prefix("vpn_load_stress_report")
    audit_fresh, audit_age = audit_log_freshness()

    report_path = STATUS_DIR / "vpn_status_report.md"

    lines = []
    lines.append("Project Status Report")
    lines.append("")
    lines.append("Project Name: AutoConnectVPN Implementation")
    lines.append(f"Date (UTC): {date_str}")
    lines.append("")
    lines.append("Progress Update:")
    lines.append("- Milestones Achieved:")

    if latest_func:
        rel = latest_func.relative_to(PROJECT_ROOT)
        lines.append(f"  - Functional test report generated: `{rel}`")
    else:
        lines.append("  - Functional tests: no report found yet.")

    if latest_load:
        rel = latest_load.relative_to(PROJECT_ROOT)
        lines.append(f"  - Load/stress test plan logged: `{rel}`")
    else:
        lines.append("  - Load/stress tests: no report found yet.")

    lines.append("")
    lines.append("- Security Audit Status:")

    if SECURITY_AUDIT_LOG.exists():
        rel = SECURITY_AUDIT_LOG.relative_to(PROJECT_ROOT)
        if audit_age is not None:
            age_str = f"{audit_age:.2f} hours"
            freshness = "FRESH" if audit_fresh else "STALE"
            lines.append(
                f"  - security_audit.log present at `{rel}` "
                f"({freshness}, {age_str} old)"
            )
        else:
            lines.append(f"  - security_audit.log present at `{rel}` (age unknown)")
    else:
        lines.append("  - security_audit.log not found (security_audit_runner.py may not have run yet).")

    lines.append("")
    lines.append("- Current Tasks:")
    lines.append("  - Run on-device functional VPN tests on real public Wi-Fi (BART, Muni, coffee shops).")
    lines.append("  - Fill in manual verification notes in the latest VPN functional test report.")
    lines.append("  - Execute at least one real load/stress test session and update the load/stress report.")
    lines.append("  - Ensure monthly security_audit_runner.py continues to run and security_audit.log stays fresh.")
    lines.append("")
    lines.append("- Issues/Challenges Faced:")
    lines.append("  - VPN CLI / OS integration not yet wired into automated tests.")
    lines.append("  - Some tests remain simulation-only and require manual device-based verification.")
    lines.append("")
    lines.append("- Next Steps:")
    lines.append("  - Decide on concrete VPN client/command interface for automation.")
    lines.append("  - Integrate real checks into vpn_functional_test_runner.py in a future iteration.")
    lines.append("  - Automate parsing of VPN logs to detect failures and anomalies.")
    lines.append("")
    lines.append(
        "Overall Status: In Progress "
        "(test plans defined; functional/load tests and security audit logging in place)"
    )
    lines.append("")
    lines.append("Additional Notes:")
    lines.append(
        "- This report is auto-generated from existing logs. Update the underlying reports "
        "by re-running the appropriate tools in the tools/ directory."
    )
    lines.append("")

    report_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"VPN status report written to: {report_path}")


if __name__ == "__main__":
    main()
